---
- name: "@{{ hostvars[borg_server_item].inventory_hostname_short }} | Create repo user"
  user:
    name: "{{ borg_server_user }}"
    create_home: yes
    skeleton: "/dev/null"
    shell: "/bin/bash"
    comment: "Borg repo for {{ inventory_hostname }}"
    home: "{{ borg_server_home }}/{{ borg_server_user }}"
    password: "!"
  delegate_to: "{{ borg_server_item }}"
  when: borg_enabled|bool

- name: "@{{ hostvars[borg_server_item].inventory_hostname_short }} | Check if user's home exists"
  stat:
    path: "{{ borg_server_home }}/{{ borg_server_user }}"
  register: repo_home_dir
  delegate_to: "{{ borg_server_item }}"
  when: not borg_enabled|bool

- name: "@{{ hostvars[borg_server_item].inventory_hostname_short }} | Deploy ssh-keys"
  authorized_key:
    user: "{{ borg_server_user }}"
    exclusive: yes
    key: "{{ (borg_manager_sshkeys|d([]) + ( [ user_ssh_key.ssh_public_key ] if borg_enabled|bool else [] )) | join('\n') | string }}"
    key_options: "restrict,command=\"/usr/local/bin/borg serve --restrict-to-repository {{ borg_server_home }}/{{ inventory_hostname_short }}/{{ borg_server_bdir }}/\""
    state: "present"
  delegate_to: "{{ borg_server_item }}"
  when: ( borg_enabled|bool
        or ( repo_home_dir.stat.exists and repo_home_dir.stat.isdir ) )

- name: "@{{ hostvars[borg_server_item].inventory_hostname_short }} | Ensure permissions"
  file:
    path: "{{ item.dir }}"
    state: "directory"
    owner: "{{ item.owner|d('root') }}"
    group: "{{ item.group|d(borg_server_user) }}"
    mode: "{{ item.mode|d('0550') }}"
    recurse: "{{ item.recurse|d('no') }}"
  with_items:
    - dir: "{{ borg_server_home }}/{{ borg_server_user }}/"
    - dir: "{{ borg_server_home }}/{{ borg_server_user }}/.ssh/"
      recurse: "yes"
    - dir: "{{ borg_server_home }}/{{ borg_server_user }}/{{ borg_server_bdir }}/"
      owner: "{{ borg_server_user }}"
      group: "{{ borg_server_user }}"
      mode: '0750'
  delegate_to: "{{ borg_server_item }}"
  when: ( borg_enabled|bool
        or ( repo_home_dir.stat.exists and repo_home_dir.stat.isdir ) )
        # This will fail if the user doesn't exists but the home-dir does.
